import json
import os
from collections import defaultdict

LEADS_FILE = "data/processed/leads.json"
MP_DATA = "data/raw/namus_missing_flat.json"
UHR_DATA = "data/raw/namus_unidentified_flat.json"
BC_DATA = "data/raw/bc_uhr_cases.json"
OUTPUT_REPORT = "data/processed/leads_report.md"

def load_data():
    print("Loading data")
    try:
        leads = json.load(open(LEADS_FILE))
        mps = json.load(open(MP_DATA))
        
        # Load UHR data
        uhr_map = {}
        # NamUs
        try:
            namus = json.load(open(UHR_DATA))
            for case in namus:
                uhr_map[case['idFormatted']] = case
        except:
            pass
            
        # BC UHR - handle structure
        try:
            bc = json.load(open(BC_DATA))
            if isinstance(bc, dict):
                for f in bc.get('features', []):
                    attr = f['attributes']
                    uhr_map[attr['CaseNumber']] = attr
        except:
            pass
            
        mp_map = {m['namus2Number']: m for m in mps}
        mp_map.update({m['idFormatted']: m for m in mps}) # fallback keys
        
        return leads, mp_map, uhr_map
    except Exception as e:
        print(f"Error loading data: {e}")
        return [], {}, {}

def generate_report():
    leads, mp_map, uhr_map = load_data()
    
    if not leads:
        print("No leads found.")
        return

    print(f"Processing {len(leads)} leads")
    
    # Enrich leads with names
    enriched = []
    for lead in leads:
        mp_id = lead['mp_id']
        mp_case = mp_map.get(mp_id)
        if not mp_case and 'MP' in mp_id:
             # Try numeric part if MP prefix
             num = int(mp_id.replace('MP', ''))
             mp_case = mp_map.get(num)
        
        name = "Unknown"
        if mp_case:
            name = f"{mp_case.get('firstName', '')} {mp_case.get('lastName', '')}".strip()
        
        lead['mp_name'] = name
        enriched.append(lead)

    # Sort by score desc
    enriched.sort(key=lambda x: x['score'], reverse=True)
    
    # Generate Markdown
    md = "# Top 50 High-Priority Leads\n\n"
    md += f"Total Matches Found: {len(enriched)}\n"
    md += "Generated by FILAMENT Enhanced Matcher (PMI + Dynamic Text Scoring)\n\n"
    
    for i, lead in enumerate(enriched[:50]):
        uhr_id = lead['uhr_id']
        mp_id = lead['mp_id']
        score = lead['score']
        
        uhr_link = f"https://www.namus.gov/UnidentifiedPersons/Case#/{uhr_id.replace('UP','').replace('MP','')}" if 'UP' in uhr_id else '#'
        mp_link = f"https://www.namus.gov/MissingPersons/Case#/{mp_id.replace('UP','').replace('MP','')}"
        
        md += f"## {i+1}. {lead['mp_name']} ({mp_id}) ↔ {uhr_id}\n"
        md += f"**Score: {score:.2f}**\n\n"
        md += f"- **MP**: [{lead['mp_name']}]({mp_link})\n"
        md += f"- **UHR**: [{uhr_id}]({uhr_link})\n"
        
        md += "### Match Reasons\n"
        for r in lead['reasons']:
            # Highlight dynamic text matches
            if "Features:" in r or "Tattoo:" in r:
                r = f"**{r}**"
            md += f"- {r}\n"
        md += "\n---\n"
        
    with open(OUTPUT_REPORT, "w") as f:
        f.write(md)
    
    print(f"Report saved to {OUTPUT_REPORT}")

if __name__ == "__main__":
    generate_report()
