import json
import argparse
import os

UHR_FILE = 'data/raw/namus_unidentified.json'
MP_FILE = 'data/raw/namus_missing.json'
DOE_FILES = [
    'data/raw/doenetwork_targeted.json',
    'data/raw/doenetwork_unidentified.json'
]


def get_val(obj, path, default="Unknown"):
    curr = obj
    for p in path.split('.'):
        if isinstance(curr, dict):
            curr = curr.get(p)
        elif isinstance(curr, list) and p.isdigit():
             idx = int(p)
             if idx < len(curr):
                 curr = curr[idx]
             else:
                 return default
        else:
            return default
    return curr if curr else default

def load_doe_network_narrative(namus_id):
    """Search Doe Network files for a matching NamUs ID."""
    if not namus_id: return None
    
    for fpath in DOE_FILES:
        if not os.path.exists(fpath): continue
        try:
            with open(fpath) as f:
                cases = json.load(f)
                for c in cases:
                    # Match NamUs ID (extracted from text)
                    if str(c.get('namus_id')) == str(namus_id):
                        return c
        except: pass
    return None

def find_case(file_path, id_val):
    print(f"Searching {file_path} for {id_val}...")
    try:
        with open(file_path) as f:
            cases = json.load(f)
            for c in cases:
                if str(c.get('namus2Number')) == str(id_val) or \
                   c.get('idFormatted') == id_val or \
                   str(c.get('id')) == str(id_val):
                    return c
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
    return None

def generate_markdown(uhr, mp):
    uhr_id = uhr.get('idFormatted')
    mp_id = mp.get('idFormatted') or f"MP{mp.get('namus2Number')}"
    mp_name = f"{get_val(mp, 'subjectIdentification.firstName')} {get_val(mp, 'subjectIdentification.lastName')}"
    
    # Enrichment
    doe_case = load_doe_network_narrative(uhr.get('namus2Number'))
    
    # Calculate Distances or Timing
    uhr_found = uhr.get('circumstances', {}).get('dateFound')
    mp_missing = mp.get('sighting', {}).get('date') or mp.get('dateOfLastContact')
    
    pmi_val = uhr.get('subjectDescription', {}).get('estimatedPostmortemInterval')
    pmi_unit = uhr.get('subjectDescription', {}).get('estimatedPostmortemIntervalUnit', {}).get('name')
    pmi_str = f"{pmi_val} {pmi_unit}" if pmi_val else "Unknown"
    
    # Features
    uhr_features = [f.get('description') for f in uhr.get('physicalFeatureDescriptions', [])]
    mp_features = [f.get('description') for f in mp.get('physicalFeatureDescriptions', [])]
    mp_tattoos = mp.get('tattoosDescription')
    if mp_tattoos: mp_features.append(f"**Tattoos Field:** {mp_tattoos}")
    
    # Clothing
    uhr_clothing = [c.get('description') for c in uhr.get('clothingAndAccessoriesArticles', [])]
    mp_clothing = [c.get('description') for c in mp.get('clothingAndAccessoriesArticles', [])] 
    
    # Narratives
    mp_circ = mp.get('circumstances', {}).get('circumstancesOfRecovery') or "No details available."
    uhr_circ = uhr.get('circumstances', {}).get('circumstancesOfRecovery') or "No details available."
    
    # Timeline Validation
    timeline_warning = ""
    try:
        from datetime import datetime
        d_missing = mp_missing
        d_found = uhr_found
        
        # Simple date parsing logic similar to match_cases.py (simplified for reporting warning only)
        # Assuming ISO format yyyy-mm-dd or similar
        if d_missing and d_found:
             # Basic string compare works for ISO, but let's be safer if possible or just use string compare for now since NamUs uses ISO
             if str(d_missing) > str(d_found):
                 timeline_warning = f"""
> [!CAUTION]
> **IMPOSSIBLE TIMELINE DETECTED**
> Missing Date ({d_missing}) matches AFTER Found Date ({d_found}).
> This match is likely invalid unless dates are erroneous.
"""
    except Exception as e:
        print(f"Warning check failed: {e}")

    doe_section = ""
    if doe_case:
        doe_section = f"""
> [!TIP]
> **Data Enrichment (Doe Network)**
> **Case ID:** [{doe_case.get('case_id')}]({doe_case.get('url')})
> 
> **Detailed Circumstances:**
> {doe_case.get('circumstances_of_discovery') or doe_case.get('raw_text')[:500] + "..."}
"""

    return f"""# Case Study: Match {uhr_id} ↔ {mp_name} ({mp_id})

> [!IMPORTANT]
> **Automated Match Report**
> This comparison was generated by the FILAMENT case study tool. Please verify all details manually.
{timeline_warning}
## 1. Demographics & Stats

| Attribute | **Missing Person ({mp_name})** | **Unidentified Remains ({uhr_id})** | Match |
| :--- | :--- | :--- | :--- |
| **Sex** | {get_val(mp, 'subjectDescription.sex.name')} | {get_val(uhr, 'subjectDescription.sex.name')} | Check |
| **Race** | {get_val(mp, 'subjectDescription.ethnicities.0.name')} | {get_val(uhr, 'subjectDescription.primaryEthnicity.name')} | Check |
| **Age** | {get_val(mp, 'subjectIdentification.currentMinAge')} - {get_val(mp, 'subjectIdentification.currentMaxAge')} (Current)<br>~{get_val(mp, 'subjectIdentification.computedMissingMinAge')} (At Disappearance) | {get_val(uhr, 'subjectDescription.estimatedAgeFrom')} - {get_val(uhr, 'subjectDescription.estimatedAgeTo')} (Estimated) | Check |
| **Height** | {get_val(mp, 'subjectDescription.heightFrom')} inches | {get_val(uhr, 'subjectDescription.heightFrom')} inches | Check |
| **Weight** | {get_val(mp, 'subjectDescription.weightFrom')} lbs | {get_val(uhr, 'subjectDescription.weightFrom')} lbs | Check |

## 2. Timeline & Location

*   **Missing Date**: {mp_missing}
*   **Found Date**: {uhr_found}
*   **PMI**: {pmi_str}

| Attribute | **Missing Person** | **Unidentified Remains** |
| :--- | :--- | :--- |
| **Location** | {get_val(mp, 'sighting.address.city')}, {get_val(mp, 'sighting.address.state.name')} | {get_val(uhr, 'circumstances.address.city')}, {get_val(uhr, 'circumstances.address.state.name')} |

## 3. Physical Evidence

### Features & Tattoos
**Missing Person:**
> {chr(10).join(['- ' + f for f in mp_features]) or "None listed"}

**Unidentified Remains:**
> {chr(10).join(['- ' + f for f in uhr_features]) or "None listed"}

### Clothing
**Missing Person:**
> {chr(10).join(['- ' + c for c in mp_clothing]) or "None listed"}

**Unidentified Remains:**
> {chr(10).join(['- ' + c for c in uhr_clothing]) or "None listed"}

## 4. Narratives
{doe_section}
**Circumstances (MP):**
{mp_circ}

**Circumstances (UHR):**
{uhr_circ}
"""

def main():
    parser = argparse.ArgumentParser(description='Generate matching case study')
    parser.add_argument('--uhr', required=True, help='Unidentified Person ID (e.g. 101894 or UP101894)')
    parser.add_argument('--mp', required=True, help='Missing Person ID (e.g. 98178 or MP98178)')
    parser.add_argument('--output', help='Output file path')
    args = parser.parse_args()
    
    # Strip prefixes if strictly numeric lookup needed, but find_case handles strings
    uhr_id = args.uhr.replace('UP', '')
    mp_id = args.mp.replace('MP', '')
    
    uhr = find_case(UHR_FILE, uhr_id)
    mp = find_case(MP_FILE, mp_id)
    
    if not uhr:
        print(f"Error: UHR case {args.uhr} not found.")
        return
    if not mp:
        print(f"Error: MP case {args.mp} not found.")
        return
        
    md = generate_markdown(uhr, mp)
    
    if args.output:
        outfile = args.output
    else:
        name = get_val(mp, 'subjectIdentification.lastName', 'Unknown')
        outfile = f"data/processed/case_study_{uhr.get('idFormatted')}_{name}.md"
        
    os.makedirs(os.path.dirname(outfile), exist_ok=True)
    with open(outfile, 'w') as f:
        f.write(md)
    print(f"Report saved to {outfile}")

if __name__ == "__main__":
    main()
