# FILAMENT Development Environment
# Podman Compose configuration for all services

services:
  # =============================================================================
  # Main Application
  # =============================================================================
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: filament-app
    volumes:
      - .:/app:Z
      - filament-cache:/home/filament/.cache
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=filament
      - POSTGRES_USER=filament
      - POSTGRES_PASSWORD=filament_dev
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=filament_dev
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - filament-net
    # Keep container running for development
    command: sleep infinity

  # =============================================================================
  # PostgreSQL with pgvector
  # =============================================================================
  postgres:
    image: docker.io/pgvector/pgvector:pg16
    container_name: filament-postgres
    environment:
      POSTGRES_DB: filament
      POSTGRES_USER: filament
      POSTGRES_PASSWORD: filament_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filament -d filament"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - filament-net

  # =============================================================================
  # Neo4j Graph Database
  # =============================================================================
  neo4j:
    image: docker.io/library/neo4j:5.15-community
    container_name: filament-neo4j
    environment:
      NEO4J_AUTH: neo4j/filament_dev
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - filament-net

  # =============================================================================
  # Ollama - Local LLM Server
  # =============================================================================
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: filament-ollama
    volumes:
      - ollama-models:/root/.ollama
    ports:
      - "11434:11434"
    # Uncomment for GPU support:
    # devices:
    #   - nvidia.com/gpu=all
    networks:
      - filament-net

# =============================================================================
# Networks
# =============================================================================
networks:
  filament-net:
    driver: bridge

# =============================================================================
# Volumes
# =============================================================================
volumes:
  postgres-data:
  neo4j-data:
  neo4j-logs:
  ollama-models:
  filament-cache:
